name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: |
          # Extract repository name and owner for base path
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          OWNER=$(echo ${{ github.repository }} | cut -d'/' -f1)
          
          # For user/org pages (repo named owner.github.io), use base=/
          # For project pages (any other repo), use base=/repo-name/
          if [ "$REPO_NAME" = "$OWNER.github.io" ]; then
            echo "Building for user/org page with base=/"
            npx vite build --base=/
          else
            echo "Building for project page with base=/$REPO_NAME/"
            npx vite build --base=/$REPO_NAME/
          fi
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
